# -*- coding: utf-8 -*-
"""ito3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y7dDcf2KtkxKsbsam2sX75lZh3UpdF3D
"""

# # Commented out IPython magic to ensure Python compatibility.
# import os
#
# # 1. Cloner ou aller dans le dossier
# if not os.path.exists('TripoSR'):
#     !git clone https://github.com/VAST-AI-Research/TripoSR.git
# # %cd TripoSR
#
# # 2. Installer manuellement TOUTES les vraies dépendances requises (sans passer par requirements.txt)
# !pip install --upgrade pip
# !pip install "Pillow>=10.2.0" omegaconf einops torchvision trimesh rembg moderngl huggingface_hub
#
# # 3. Installer torchmcubes proprement
# !pip uninstall -y torchmcubes
# !pip install git+https://github.com/tatsy/torchmcubes.git
#
# # 1. Forcer les versions exactes de Hugging Face et transformers attendues par TripoSR
# !pip install --upgrade transformers==4.38.2 huggingface-hub==0.22.2
#
# !pip install xatlas
#
# !pip install --upgrade onnxruntime
#
# pip freeze > req.txt
#
# !cat req.txt
#
# !python run.py examples/chair.png --output-dir output/ --device cuda
#
# import os
#
# print("--- Recherche du dossier output dans /content/ ---")
# for root, dirs, files in os.walk("/content"):
#     if "output" in dirs:
#         print(f"Trouvé ici : {os.path.join(root, 'output')}")
#
# import os
#
# file_path = '/content/TripoSR/TripoSR/TripoSR/TripoSR/output/0/mesh.obj'
#
# if os.path.exists(file_path):
#     size_bytes = os.path.getsize(file_path)
#     if size_bytes < 1024:
#         size_human_readable = f"{size_bytes} Bytes"
#     elif size_bytes < 1024 * 1024:
#         size_human_readable = f"{size_bytes / 1024:.2f} KB"
#     elif size_bytes < 1024 * 1024 * 1024:
#         size_human_readable = f"{size_bytes / (1024 * 1024):.2f} MB"
#     else:
#         size_human_readable = f"{size_bytes / (1024 * 1024 * 1024):.2f} GB"
#     print(f"La taille du fichier {file_path} est : {size_human_readable}")
# else:
#     print(f"Le fichier {file_path} n'existe pas.")
